local Player = require("player")
local Circle = require("Circle")
local Blocks = require("blocks")
local ScoreSys = require("ScoreSys")
num = 0
function love.load()
  scoresystem = ScoreSys.new()
  player = Player.new()
  circle = Circle.new()
  blocks = Blocks.new()
end
function love.update(dt)
  player:update(dt)
  circle:update(dt)
  blocks:update(dt)
  scoresystem:update(dt)
  --Colliding(player,tile)
end
function love.draw()
  player:draw()
  circle:draw()
  blocks:draw()
  scoresystem:draw()
end
--A project by Louis Andrew (GODTIER)